#Preliminary Data Exploration and Data Cleaning

Importing pandas and reading the csv file.

In [46]:
import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')

Looking at the top of the dataframe.

In [47]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

To see the number of rows and column.

In [48]:
df.shape

(51, 6)

Accessing the column names.

In [49]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

# Missing values and junk data.

Finding the NaN cells.
(Blank cells or cells with string values.)

In [53]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

Checking the last rows.

In [54]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

Deleting the last row.

In [55]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

#Accessing columns and particular cells.

Accessing a partiicular column.

In [56]:
clean_df['Starting Median Salary']

0    46,000.00
1    57,700.00
2    42,600.00
3    36,800.00
4    41,600.00
5    35,800.00
6    38,800.00
7    43,000.00
8    63,200.00
9    42,600.00
10   53,900.00
11   38,100.00
12   61,400.00
13   55,900.00
14   53,700.00
15   35,000.00
16   35,900.00
17   50,100.00
18   34,900.00
19   60,900.00
20   38,000.00
21   37,900.00
22   47,900.00
23   39,100.00
24   41,200.00
25   43,500.00
26   35,700.00
27   38,800.00
28   39,200.00
29   37,800.00
30   57,700.00
31   49,100.00
32   36,100.00
33   40,900.00
34   35,600.00
35   49,200.00
36   40,800.00
37   45,400.00
38   57,900.00
39   35,900.00
40   54,200.00
41   39,900.00
42   39,900.00
43   74,300.00
44   50,300.00
45   40,800.00
46   35,900.00
47   34,100.00
48   36,500.00
49   34,000.00
Name: Starting Median Salary, dtype: float64

To find the highest starting salary.

In [57]:
clean_df['Starting Median Salary'].max()

74300.0

Too find the index of the highest salary.

In [58]:
clean_df['Starting Median Salary'].idxmax()

np.int64(43)

To see the name of the  major at loation 43.

In [59]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

Using a different method.

In [60]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

Using .loc to access an entire  row.

In [61]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                         74,300.00
Mid-Career Median Salary                       91,700.00
Mid-Career 10th Percentile Salary              66,400.00
Mid-Career 90th Percentile Salary             124,000.00
Group                                               STEM
Name: 43, dtype: object

*What college major has the highest mid-career salary? How much do graduates with this major earn? (Mid-career is defined as having 10+ years of experience).*

In [62]:
clean_df['Mid-Career Median Salary'].idxmax()

np.int64(8)

In [63]:
clean_df['Undergraduate Major'].loc[8]

'Chemical Engineering'

*Which college major has the lowest starting salary and how much do graduates earn after university?*

In [64]:
clean_df['Starting Median Salary'].idxmin()

np.int64(49)

In [65]:
clean_df['Undergraduate Major'].loc[49]

'Spanish'

In [66]:
clean_df['Mid-Career Median Salary'].loc[49]

np.float64(53100.0)

*Which college major has the lowest mid-career salary and how much can people expect to earn with this degree? *

In [67]:
clean_df['Mid-Career Median Salary'].idxmin()

np.int64(18)

In [68]:
clean_df['Undergraduate Major'].loc[18]

'Education'

In [69]:
clean_df['Starting Median Salary'].loc[18]
clean_df['Mid-Career 90th Percentile Salary'].loc[18]

np.float64(102000.0)

#Sorting Values and Adding columns

**Lowest Risk Majors**

A low-risk major is a degree where there is a small difference between the lowest and highest salaries. In other words, if the difference between the 10th percentile and the 90th percentile earnings of your major is small, then you can be more certain about your salary after you graduate.

In [70]:
clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

0    109,800.00
1     96,700.00
2    113,700.00
3    104,200.00
4     85,400.00
5     96,200.00
6     98,100.00
7    108,200.00
8    122,100.00
9    102,700.00
10    84,600.00
11   105,500.00
12    95,900.00
13    98,000.00
14   114,700.00
15    74,800.00
16   116,300.00
17   159,400.00
18    72,700.00
19    98,700.00
20    99,600.00
21   102,100.00
22   147,800.00
23    70,000.00
24    92,000.00
25   111,000.00
26    76,000.00
27    66,400.00
28   112,000.00
29    88,500.00
30   115,900.00
31    84,500.00
32    71,300.00
33   118,800.00
34   106,600.00
35   100,700.00
36   132,900.00
37   137,800.00
38    99,300.00
39   107,300.00
40    50,700.00
41    65,300.00
42   132,500.00
43    57,600.00
44   122,000.00
45   126,800.00
46    95,400.00
47    66,700.00
48    87,300.00
49    65,400.00
dtype: float64

Using .subtract() method.

In [71]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

0    109,800.00
1     96,700.00
2    113,700.00
3    104,200.00
4     85,400.00
5     96,200.00
6     98,100.00
7    108,200.00
8    122,100.00
9    102,700.00
10    84,600.00
11   105,500.00
12    95,900.00
13    98,000.00
14   114,700.00
15    74,800.00
16   116,300.00
17   159,400.00
18    72,700.00
19    98,700.00
20    99,600.00
21   102,100.00
22   147,800.00
23    70,000.00
24    92,000.00
25   111,000.00
26    76,000.00
27    66,400.00
28   112,000.00
29    88,500.00
30   115,900.00
31    84,500.00
32    71,300.00
33   118,800.00
34   106,600.00
35   100,700.00
36   132,900.00
37   137,800.00
38    99,300.00
39   107,300.00
40    50,700.00
41    65,300.00
42   132,500.00
43    57,600.00
44   122,000.00
45   126,800.00
46    95,400.00
47    66,700.00
48    87,300.00
49    65,400.00
dtype: float64

Adding this column to the dataframe using .insert() method.

In [72]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"109,800.00","46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"113,700.00","42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"104,200.00","36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"85,400.00","41,600.00","76,800.00","50,600.00","136,000.00",Business

Sorting the lowest spread.

In [73]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major    Spread
40                     Nursing 50,700.00
43         Physician Assistant 57,600.00
41                   Nutrition 65,300.00
49                     Spanish 65,400.00
27  Health Care Administration 66,400.00

 **Challenge**

*Using the .sort_values() method, can you find the degrees with the highest potential? Find the top 5 degrees with the highest values in the 90th percentile.*

*Also, find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation.*

In [74]:
clean_df.sort_values('Mid-Career 90th Percentile Salary').head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,"65,400.00","34,000.00","53,100.00","31,000.00","96,400.00",HASS
47,Religion,"66,700.00","34,100.00","52,000.00","29,700.00","96,400.00",HASS
40,Nursing,"50,700.00","54,200.00","67,000.00","47,600.00","98,300.00",Business
41,Nutrition,"65,300.00","39,900.00","55,300.00","33,900.00","99,200.00",HASS
27,Health Care Administration,"66,400.00","38,800.00","60,600.00","34,600.00","101,000.00",Business

In [75]:
clean_df.sort_values('Spread', ascending=False).head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
17,Economics,"159,400.00","50,100.00","98,600.00","50,600.00","210,000.00",Business
22,Finance,"147,800.00","47,900.00","88,300.00","47,200.00","195,000.00",Business
37,Math,"137,800.00","45,400.00","92,400.00","45,200.00","183,000.00",STEM
36,Marketing,"132,900.00","40,800.00","79,600.00","42,100.00","175,000.00",Business
42,Philosophy,"132,500.00","39,900.00","81,200.00","35,500.00","168,000.00",HASS

In [76]:
clean_df.sort_values('Mid-Career Median Salary', ascending=False).head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
8,Chemical Engineering,"122,100.00","63,200.00","107,000.00","71,900.00","194,000.00",STEM
12,Computer Engineering,"95,900.00","61,400.00","105,000.00","66,100.00","162,000.00",STEM
19,Electrical Engineering,"98,700.00","60,900.00","103,000.00","69,300.00","168,000.00",STEM
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
17,Economics,"159,400.00","50,100.00","98,600.00","50,600.00","210,000.00",Business

#Grouping and Pivoting Data with Pandas

How many majors in each category?

In [77]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

Average salary by group.

*There was an error  in calculating mean because Undergratuate majors are non numeric values and their mean could not be coomputed. So I removed the column.*

In [78]:
pd.options.display.float_format = '{:,.2f}'.format
new_df = clean_df.drop('Undergraduate Major', axis=1)
new_df.groupby('Group').mean()

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"